export const SELECIONAR_FOTO= 'SELECIONAR_FOTO';

export const CARREGAR_ALBUNS_INICIO= 'CARREGAR_ALBUNS_INICIO';
export const CARREGAR_ALBUNS_SUCESSO= 'CARREGAR_ALBUNS_SUCESSO';
export const CARREGAR_ALBUNS_ERRO= 'CARREGAR_ALBUNS_ERRO';
